name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test
      env:
        MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}
        MAILGUN_DOMAIN: ${{secrets.MAILGUN_DOMAIN}}
        TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
        SECRET: ${{secrets.SECRET}}
        TEST_EMAIL: ${{secrets.TEST_EMAIL}}
        PUBLIC_APPLY_EMAIL: ${{secrets.PUBLIC_APPLY_EMAIL}}
        CONTACT_FORM_HANDLER_EMAIL: ${{secrets.CONTACT_FORM_HANDLER_EMAIL}}
        PROD_EMAIL: ${{secrets.PROD_EMAIL}}
        LIQPAY_PUBLIC_KEY: ${{secrets.LIQPAY_PUBLIC_KEY}}
        LIQPAY_PRIVATE_KEY: ${{secrets.LIQPAY_PRIVATE_KEY}}
